version: '2'

services:
  rabbitmq-dev:
    image: registry2.swarm.devfactory.com/devfactory/rabbitmq/rabbitmq-ds:latest
    container_name: rabbitmq-dev
    ports:
      - 5672
      - 5005
    volumes:
      - ..:/data:Z
    command: bash
    tty: true
